AWSTemplateFormatVersion: '2010-09-09'
Description: Creates AWS Glue resources.  **WARNING**  You will be billed for the
  AWS resources used if you create a stack from this template.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment Configuration conf
        Parameters:
          - EnvironmentTypeconf
    ParameterLabels:
      EnvironmentType:
        default: environment type conf
Parameters:
  EnvironmentType:
    Description: Enter the CloudCheckr 3rd party External ID
    Type: String
    Default: ''

# Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.



  S3ETLScriptPath:
    Type: String
#    MinLength: ''
    Default: ''
    Description: "Location of the Glue job ETL scripts in S3."
    # location crawlertesttarget123

  S3ETLOutputPath:
    Type: String
#    MinLength: ''
    Default: ''
    Description: "Name of the S3 output path to which this CloudFormation template's AWS Glue jobs are going to write ETL output."
    #location jobs-glue-hlsdxc

  #SourceDataBucketName:
#  Type: String
#    MinLength: "1"
##    #location crawlertesttarget12345

Resources:

  AWSGlueJobRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - glue.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AdministratorAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Path: "/"

#  GHCDatabase:
#    Type: "AWS::Glue::Database"
#    Properties:
#      DatabaseInput:
#        Description: "Marketing and Sales database (Amazon QuickSight Samples)."
#        Name: !Ref MarketingForGHCClient
#      CatalogId: !Ref AWS::AccountId

  GHCDXCDataJob:
    Type: "AWS::Glue::Job"
    Properties:
      Role: !Ref AWSGlueJobRole
      Name: "glue-job-etl"
      Command: {
        Name: "glueetl",
        "ScriptLocation" : !Sub "${S3ETLScriptPath}/ghcdxcetl.py"
      }
#      DefaultArguments: {
#          "--database_name" : !Ref MarketingForGHCClient,
#          "--s3_output_path" : !Sub "${S3ETLOutputPath}/jobs-glue-hlsdxc"
#          "--s3_sales_data_path" : !Sub "${S3ETLOutputPath}/processdata",
#          "--s3_marketing_data_path" : !Sub "${S3ETLOutputPath}/rawdata"
#      }
      MaxRetries: 0
      Description: "Join Marketing and Sales data."
      AllocatedCapacity: 5

  OnDemandJobTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: ON_DEMAND
      Description: DESCRIPTION_ON_DEMAND
      Actions:
        - JobName: !Ref GHCDXCDataJob
      Name: prod-trigger1-ondemand
