AWSTemplateFormatVersion: 2010-09-09
Description: Billing-BillingCustomSubscriptions Template.
  This creates Custom Subscriptions to Billing SNS Topics.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Stack Dependencies
        Parameters:
          - BillingTopicsStackName
      - Label:
          default: Subscription Configuration
        Parameters:
          - TopicTestEmailEndpoint
          - SMSTopicTestSMSEndpoint
    ParameterLabels:
      BillingTopicsStackName:
        default: Billing Topics Stack Name
      TopicTestEmailEndpoint:
        default: Topic Test Email Endpoint
      SMSTopicTestSMSEndpoint:
        default: SMS Topic Test SMS Endpoint
Parameters:
  BillingTopicsStackName:
    Description: Name of the CloudFormation Stack containing Billing Topics
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: BillingTopics
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  TopicTestEmailEndpoint:
    Description: Optional test email Endpoint for Topics. If specified, test Subscriptions will be created instead of normal Subscriptions. Use hyphen to skip
    Type: String
    Default: ''
    AllowedPattern: (^$|^-$|[^\s@]+@[^\s@]+\.[^\s@]+$)
    ConstraintDescription: must be a valid email address.
  SMSTopicTestSMSEndpoint:
    Description: Optional test SMS Endpoint for SMS Topics. If specified, test Subscriptions will be created instead of normal Subscriptions. Use hyphen to skip
    Type: String
    Default: ''
    #AllowedPattern: (^$|^-$|^(\+\d{1,2}[\s.-]?)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}$)
    AllowedPattern: (^$|^-$|^\+\d{11,12}$)
    ConstraintDescription: must be a valid phone number.
Rules:
  ValidateRegion:
    Assertions:
      - Assert: !Equals [ !Ref 'AWS::Region', us-east-1 ]
        AssertDescription: This Template can only be used in Region us-east-1.
Conditions:
  ConfigureNormalTopicSubscriptions: !Equals [ !Ref TopicTestEmailEndpoint, '' ]
  ConfigureTestTopicSubscriptions: !And [ !Not [ !Condition ConfigureNormalTopicSubscriptions ],
                                          !Not [ !Equals [ !Ref TopicTestEmailEndpoint, '-' ]]]
  ConfigureNormalSNSTopicSubscriptions: !Equals [ !Ref SMSTopicTestSMSEndpoint, '' ]
  ConfigureTestSNSTopicSubscriptions: !And [ !Not [ !Condition ConfigureNormalSNSTopicSubscriptions ],
                                             !Not [ !Equals [ !Ref SMSTopicTestSMSEndpoint, '-' ]]]
Resources:
  BillsTopicTestEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !ImportValue
        Fn::Sub: ${BillingTopicsStackName}-BillsTopic
      Protocol: email
      Endpoint: !Ref TopicTestEmailEndpoint
    Condition: ConfigureTestTopicSubscriptions
  BillsTopicMCrawfordEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !ImportValue
        Fn::Sub: ${BillingTopicsStackName}-BillsTopic
      Protocol: email
      Endpoint: mcrawford@dxc.com
    Condition: ConfigureNormalTopicSubscriptions
  BillsSMSTopicTestSMSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !ImportValue
        Fn::Sub: ${BillingTopicsStackName}-BillsSMSTopic
      Protocol: sms
      Endpoint: !Ref SMSTopicTestSMSEndpoint
    Condition: ConfigureTestSNSTopicSubscriptions
  BillsSMSTopicMCrawfordSMSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !ImportValue
        Fn::Sub: ${BillingTopicsStackName}-BillsSMSTopic
      Protocol: sms
      Endpoint: '+14156525483'
    Condition: ConfigureNormalSNSTopicSubscriptions
