AWSTemplateFormatVersion: 2010-09-09
Description: Common-TagFunctions Template.
  This creates Lambda Functions related to Tagging Resources.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Stack Dependencies
        Parameters:
          - BucketsStackName
      - Label:
          default: Function Configuration
        Parameters:
          - VpcDefaultResourceTaggerFunctionKey
          - VpcDefaultResourceTaggerFunctionObjectVersion
    ParameterLabels:
      BucketsStackName:
        default: Buckets Stack Name
      VpcDefaultResourceTaggerFunctionKey:
        default: VpcDefaultResourceTagger Function S3 Key
      VpcDefaultResourceTaggerFunctionObjectVersion:
        default: VpcDefaultResourceTagger Function S3 Object Version
Parameters:
  BucketsStackName:
    Description: Name of the CloudFormation Stack containing Buckets
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: Buckets
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  VpcDefaultResourceTaggerFunctionKey:
    Description: Key of Object within the S3 Bucket containing the VpcDefaultResourceTagger Lambda Function zipfile
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: VpcDefaultResourceTagger.zip
    AllowedPattern: ^[-_.a-zA-Z0-9]*\.zip$
    ConstraintDescription: must be a valid zipfilename, not containing slashes.
  VpcDefaultResourceTaggerFunctionObjectVersion:
    Description: Version of Object within the S3 Bucket containing the VpcDefaultResourceTagger Lambda Function zipfile
    Type: String
    MaxLength: 32
    Default: ''
    ConstraintDescription: must be a valid S3 Object Version.
Conditions:
  ConfigureVpcDefaultResourceTaggerFunctionObjectVersion: !Not [ !Equals [ !Ref VpcDefaultResourceTaggerFunctionObjectVersion, '' ]]
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: TagVpcDefaultResourcesPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeRouteTables
                  - ec2:DescribeNetworkAcls
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeTags
                  - ec2:CreateTags
                Resource: '*'
  VpcDefaultResourceTaggerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: VpcDefaultResourceTagger
      Description: A Lambda function that tags the default resources created along with a VPC, which are otherwise untagged.
      Role: !GetAtt Role.Arn
      Runtime: nodejs8.10
      Timeout: 30
      Handler: VpcDefaultResourceTagger.handler
      Code:
        S3Bucket: !ImportValue
          Fn::Sub: ${BucketsStackName}-FunctionsBucket
        S3Key: !Ref VpcDefaultResourceTaggerFunctionKey
        S3ObjectVersion: !If [ ConfigureVpcDefaultResourceTaggerFunctionObjectVersion, !Ref VpcDefaultResourceTaggerFunctionObjectVersion, !Ref 'AWS::NoValue' ]
Outputs:
  VpcDefaultResourceTaggerFunctionArn:
    Description: The VpcDefaultResourceTagger Lambda Function ARN
    Value: !GetAtt VpcDefaultResourceTaggerFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-VpcDefaultResourceTaggerFunctionArn
