AWSTemplateFormatVersion: 2010-09-09
Description: Example-IdentifierConverterCustomResource Template.
  This demonstrates how to use the IdentifierConverter Lambda Function to create a HostName for Instances from other Template Identifiers.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: System Configuration
        Parameters:
          - CompanyName
          - LocationName
          - SystemName
      - Label:
          default: Environment Configuration
        Parameters:
          - EnvironmentName
      - Label:
          default: Application Configuration
        Parameters:
          - ApplicationName
          - ComponentName
    ParameterLabels:
      CompanyName:
        default: Company Name
      LocationName:
        default: Location Name
      SystemName:
        default: System Name
      EnvironmentName:
        default: Environment Name
      ApplicationName:
        default: Application Name
      ComponentName:
        default: Component Name
Parameters:
  CompanyName:
    Description: Name of the Company
    Type: String
    MinLength: 2
    MaxLength: 32
    Default: HLS
    AllowedPattern: ^[A-Z][a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters.
  LocationName:
    Description: Optional Name of the Location (defaults to AWS Region)
    Type: String
    Default: ''
    AllowedValues: # More values are allowed, this is a subset for testing. See the Lambda function for full set.
      - ''
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - eu-west-1
      - SantaBarbara
      - NewYork
      - SanFrancisco
      - LosAngeles
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters or dashes, if specified.
  SystemName:
    Description: Optional Name of the System
    Type: String
    MaxLength: 32
    Default: ''
    AllowedPattern: (^$|^[A-Z][a-zA-Z0-9]*$)
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters, if specified.
  EnvironmentName:
    Description: Name of the Environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - UAT
      - Testing
      - Development
      - Build
      - Core
      - Recovery
      - Log
      - Identity
    ConstraintDescription: must be Production, Staging, UAT, Testing, Development, Build, Core, Recovery, Log or Identity.
  ApplicationName:
    Description: Name of the Application
    Type: String
    MinLength: 2
    MaxLength: 32
    Default: DeepSecurity
    AllowedPattern: ^[A-Z][a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters.
  ComponentName:
    Description: Optional Name of the Component
    Type: String
    MaxLength: 32
    Default: Database
    AllowedPattern: (^$|^[A-Z][a-zA-Z0-9]*$)
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters, if specified.
Conditions:
  ConfigureLocationName: !Not [ !Equals [ !Ref LocationName, '' ]]
  ConfigureSystemName: !Not [ !Equals [ !Ref SystemName, '' ]]
  ConfigureComponentName: !Not [ !Equals [ !Ref ComponentName, '' ]]
Resources:
  IdentifierConverter:
    Type: Custom::IdentifierConverter
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:IdentifierConverter
      CompanyName: !Ref CompanyName
      LocationName: !If [ ConfigureLocationName, !Ref LocationName, !Ref 'AWS::NoValue' ]
      SystemName: !If [ ConfigureSystemName, !Ref SystemName, !Ref 'AWS::NoValue' ]
      EnvironmentName: !Ref EnvironmentName
      ApplicationName: !Ref ApplicationName
      ComponentName: !If [ ConfigureComponentName, !Ref ComponentName, !Ref 'AWS::NoValue' ]
Outputs:
  CompanyCode:
    Description: The CompanyCode
    Value: !GetAtt IdentifierConverter.CompanyCode
  CompanyNameLowerCase:
    Description: The CompanyName in LowerCase
    Value: !GetAtt IdentifierConverter.CompanyNameLowerCase
  SystemCode:
    Description: The SystemCode
    Value: !GetAtt IdentifierConverter.SystemCode
  SystemNameLowerCase:
    Description: The SystemName in LowerCase
    Value: !GetAtt IdentifierConverter.SystemNameLowerCase
  LocationCode:
    Description: The LocationCode
    Value: !GetAtt IdentifierConverter.LocationCode
  LocationNameLowerCase:
    Description: The LocationName in LowerCase
    Value: !GetAtt IdentifierConverter.LocationNameLowerCase
  EnvironmentCode:
    Description: The EnvironmentCode
    Value: !GetAtt IdentifierConverter.EnvironmentCode
  EnvironmentNameLowerCase:
    Description: The EnvironmentName in LowerCase
    Value: !GetAtt IdentifierConverter.EnvironmentNameLowerCase
  ApplicationCode:
    Description: The ApplicationCode
    Value: !GetAtt IdentifierConverter.ApplicationCode
  ApplicationNameLowerCase:
    Description: The ApplicationName in LowerCase
    Value: !GetAtt IdentifierConverter.ApplicationNameLowerCase
  ComponentCode:
    Description: The ComponentCode
    Value: !GetAtt IdentifierConverter.ComponentCode
  ComponentNameLowerCase:
    Description: The ComponentName in LowerCase
    Value: !GetAtt IdentifierConverter.ComponentNameLowerCase
