AWSTemplateFormatVersion: 2010-09-09
Description: Example-HostedZoneDelegationCustomResource Template.
  This demonstrates how to create a sub-domain delegation in a Parent HostedZone via a Custom Resource.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Function Configuration
        Parameters:
          - Name
          - DomainName
    ParameterLabels:
      Name:
        default: Name
      DomainName:
        default: Domain Name
Parameters:
  Name:
    Description: Name of the Environment associated with the Stack
    Type: String
    Default: Development
    AllowedValues:
      - Production
      - Staging
      - UAT
      - Testing
      - Development
      - Build
      - Core
      - Recovery
      - Log
      - Identity
      - Management
      - Organization
    ConstraintDescription: must be Production, Staging, UAT, Testing, Development, Build, Core, Recovery, Log, Identity, Management or Organization.
  PublicDomain:
    Description: Name of the Public Domain
    Type: String
    Default: d.us-west-2.hlsb.dxcanalytics.com
Resources:
  PublicHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Sub Public Zone for ${PublicDomain}
      Name: !Sub ${PublicDomain}.
      HostedZoneTags:
        - Key: Name
          Value: !Sub ${Name}-PublicHostedZone
  PublicHostedZoneDelegation:
    Type: Custom::HostedZoneDelegation
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:HostedZoneDelegation
      DomainName: !Ref PublicDomain
      NameServers: !GetAtt PublicHostedZone.NameServers
Outputs:
  PublicDomain:
    Description: The PublicDomain
    Value: !Ref PublicDomain
    Export:
      Name: !Sub ${AWS::StackName}-PublicDomain
  PublicHostedZone:
    Description: The PublicHostedZone
    Value: !Ref PublicHostedZone
    Export:
      Name: !Sub ${AWS::StackName}-PublicHostedZone
