AWSTemplateFormatVersion: 2010-09-09
Description: Example-HostNameCustomResource Template.
  This demonstrates how to use the HostName Lambda Function to create a HostName for Instances based on Template Properties which complies with a standard naming convention.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: System Configuration
        Parameters:
          - CompanyName
          - LocationName
          - SystemName
      - Label:
          default: Environment Configuration
        Parameters:
          - EnvironmentName
      - Label:
          default: Application Configuration
        Parameters:
          - ApplicationName
          - ComponentName
      - Label:
          default: Instance Configuration
        Parameters:
          - InstanceNumber
          - ZoneCode
    ParameterLabels:
      CompanyName:
        default: Company Name
      LocationName:
        default: Location Name
      SystemName:
        default: System Name
      EnvironmentName:
        default: Environment Name
      ApplicationName:
        default: Application Name
      ComponentName:
        default: Component Name
      InstanceNumber:
        default: Instance Number
      ZoneCode:
        default: Zone Code
Parameters:
  CompanyName:
    Description: Name of the Company
    Type: String
    MinLength: 2
    MaxLength: 32
    Default: HLS
    AllowedPattern: ^[A-Z][a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters.
  LocationName:
    Description: Optional Name of the Location (defaults to AWS Region)
    Type: String
    Default: ''
    AllowedValues: # More values are allowed, this is a subset for testing. See the Lambda function for full set.
      - ''
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - eu-west-1
      - SantaBarbara
      - NewYork
      - SanFrancisco
      - LosAngeles
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes, if specified.
  SystemName:
    Description: Optional Name of the System
    Type: String
    MaxLength: 32
    Default: ''
    AllowedPattern: (^$|^[A-Z][a-zA-Z0-9]*$)
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters, if specified.
  EnvironmentName:
    Description: Name of the Environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - UAT
      - Testing
      - Development
      - Build
      - Core
      - Recovery
      - Log
      - Identity
    ConstraintDescription: must be Production, Staging, UAT, Testing, Development, Build, Core, Recovery, Log or Identity.
  ApplicationName:
    Description: Name of the Application
    Type: String
    MinLength: 2
    MaxLength: 32
    Default: DeepSecurity
    AllowedPattern: ^[A-Z][a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters.
  ComponentName:
    Description: Optional Name of the Component
    Type: String
    MaxLength: 32
    Default: Database
    AllowedPattern: (^$|^[A-Z][a-zA-Z0-9]*$)
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters, if specified.
  InstanceNumber:
    Description: Optional Number of the Instance
    Type: String
    Default: ''
    AllowedPattern: (^$|^[0-9]{1,2}$)
    ConstraintDescription: must be an integer between 0 and 99, or blank.
  ZoneCode:
    Description: Optional Letter indicating the Availability Zone
    Type: String
    Default: ''
    AllowedValues:
      - ''
      - a
      - b
      - c
      - d
      - e
      - f
    ConstraintDescription: must be a lower-case letter between a and f, if specified.
Conditions:
  ConfigureLocationName: !Not [ !Equals [ !Ref LocationName, '' ]]
  ConfigureSystemName: !Not [ !Equals [ !Ref SystemName, '' ]]
  ConfigureComponentName: !Not [ !Equals [ !Ref ComponentName, '' ]]
  ConfigureInstanceNumber: !Not [ !Equals [ !Ref InstanceNumber, '' ]]
  ConfigureZoneCode: !Not [ !Equals [ !Ref ZoneCode, '' ]]
Resources:
  HostName:
    Type: Custom::HostName
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:HostName
      CompanyName: !Ref CompanyName
      LocationName: !If [ ConfigureLocationName, !Ref LocationName, !Ref 'AWS::NoValue' ]
      SystemName: !If [ ConfigureSystemName, !Ref SystemName, !Ref 'AWS::NoValue' ]
      EnvironmentName: !Ref EnvironmentName
      ApplicationName: !Ref ApplicationName
      ComponentName: !If [ ConfigureComponentName, !Ref ComponentName, !Ref 'AWS::NoValue' ]
      InstanceNumber: !If [ ConfigureInstanceNumber, !Ref InstanceNumber, !Ref 'AWS::NoValue' ]
      ZoneCode: !If [ ConfigureZoneCode, !Ref ZoneCode, !Ref 'AWS::NoValue' ]
Outputs:
  HostName:
    Description: The HostName
    Value: !Ref HostName
